### PR TITLE
Add jitsi-universe as parent, remove hard coded versions

### PR DESCRIPTION
**Pull request by champtar**
Signed-off-by: Etienne CHAMPETIER champetier.etienne@gmail.com

### CODE REVIEW

**Comment by ibauersachs** [comment]
I'm not keen on merging this. Thr pom comes from the upstream project and I'd try to keep changes to it to a minimum.

Additionally, the only reason we use a fork currently is because upstream hasn't released a version with our patch yet (but the patch has been accepted and committed).

**Comment by champtar** [comment]
They seem to be slow to release ...

**Comment by ibauersachs** [comment]
'They' is Brian Wellington and he releases when there have been enough changes to make his effort on SourceForge worthwhile. He actively refuses to use a proper source layout, Maven (Central) or anything modern. The current Maven releases and pom are from me and Noa Resare at Spotify.

**Comment by champtar** [comment]
Thanks for the info, closing this PR

**Pull request closed without merging**
